# Generated by Django 5.2.6 on 2025-09-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartera',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='fecha_alta',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='marca',
        ),
        migrations.AddField(
            model_name='cartera',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='carteras/'),
        ),
    ]
