# Generated by Django 5.2.6 on 2025-09-21 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_cartera_color_remove_cartera_fecha_alta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartera',
            name='imagen',
        ),
    ]
